v = input("Digite algo: ")

num = v.isnumeric()
alnum = v.isalnum()
tipo = type(v)
espaco = v.isspace()
alfa = v.isalpha()
mai = v.isupper()
mini = v.islower()
titulo = v.istitle()

print("O tipo de caracter de {} é: ".format(v), tipo)
print("{} tem espaços: ".format(v), espaco)
print("{} é um numero: ".format(v), num)
print("{} é alfabetico: ".format(v), alfa)
print("{} é alfanumerico: ".format(v), alnum)
print("{} esta maiusculo: ".format(v), mai)
print("{} esta minuscula: ".format(v), mini)
print("{} esta capitalizada (1 letra maiuscula): ".format(v), titulo)

a = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está capitalizado? {a.istitle()}')
